//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_Chat__1_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int messageId { get; set; }
        public int messFromUser { get; set; }
        public int messToUser { get; set; }
        public string messageBody { get; set; }
        public System.DateTime messTime { get; set; }
        public string imagePath { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
